# Filename: store_para_lookup_tbl_json.py
"""Summary: store parameter lookup tables to json files
Structure of the 

"""
# Author: Da Zhang, PhD, DABR
# Created: Fri Apr 22 16:57:14 2022
# Last-Updated: Mon Aug 22 14:10:06 2022 (-14400 Eastern Daylight Time)
# Update #: 

#CHANGE LOOKUP TABLE
# ONE TABLE, TUBE A AND TUBE B FOR ONLY RELEVANT DIFFERENT PARAMETERS
# KV, MAS, FILTER(?)

import json

topo_lookup_tbl = {"Range": ("get_para_from_indiv_prot_xml_GE_Optima", {"para_xpath": "^groupType",
                                                                        "in_group": True,
                                                                        "in_recon": False}),

                   "Tube Position (Angle)": ("get_para_from_indiv_prot_xml_GE_Optima", {"para_xpath": "^scoutPlane",
                                                                                        "in_group": True,
                                                                                        "in_recon": False}),

                   "kVp": ("get_para_from_indiv_prot_xml_GE_Optima", {"para_xpath": "^kiloVolts",
                                                                      "in_group": True,
                                                                      "in_recon": False}),

                   "mA": ("get_para_from_indiv_prot_xml_GE_Optima", {"para_xpath": "^milliAmps =",
                                                                     "in_group": True,
                                                                     "in_recon": False}),
                   
                   # "Kernel": ("get_para_from_indiv_prot_xml_GE_Optima", {"para_xpath": "^Kernel:",
                   #                                                       "in_group": "True"}),
                   
                   "Series Description": ("get_para_from_indiv_prot_xml_GE_Optima", {"para_xpath": "^seriesDescriptionRecon",
                                                                                     "in_group": True,
                                                                                     "in_recon": False})
                   }

scan_lookup_tbl = {"Range": ("get_para_from_indiv_prot_xml_GE_Optima", {"para_xpath": "^seriesDescriptionRecon",
                                                                        "in_group": True,
                                                                        "in_recon": False}),
                   # "Scan Mode": ("calculate_scan_para_Siemens_Force", {}),
                   # "Reference kVp": ("get_para_from_indiv_prot_xml_GE_Optima", {"para_xpath": "^AutokVVoltage:",
                   #                                                              "in_group": "True"}),
                   
                   "kVp": ("get_para_from_indiv_prot_xml_GE_Optima", {"para_xpath": "^kiloVolts",
                                                                      "in_group": True,
                                                                      "in_recon": False}),
                   
                   "Auto kV Mode": ("get_para_from_indiv_prot_xml_GE_Optima", {"para_xpath": "^kvModulationMode",
                                                                               "in_group": True,
                                                                               "in_recon": False}),
                   
                   # "Qref mAs": ("get_para_from_indiv_prot_xml_GE_Optima", {"para_xpath": "^AECReferenceMAs:",
                   #                                                         "in_group": "True"}),
                   
                   "Noise Index": ("get_para_from_indiv_prot_xml_GE_Optima", {"para_xpath": "^automaNoiseIndex",
                                                                           "in_group": True,
                                                                           "in_recon": False}),
                   
                   "Reference Noise Index": ("get_para_from_indiv_prot_xml_GE_Optima", {"para_xpath": "^automaReferenceNoiseIndex",
                                                                           "in_group": True,
                                                                           "in_recon": False}),
                   
                   "Auto mA minimum": ("get_para_from_indiv_prot_xml_GE_Optima", {"para_xpath": "^automaMinMilliAmps",
                                                                               "in_group": True,
                                                                               "in_recon": False}),
                   
                   "Auto mA maximum": ("get_para_from_indiv_prot_xml_GE_Optima", {"para_xpath": "^automaMaxMilliAmps",
                                                                               "in_group": True,
                                                                               "in_recon": False}),
                   
                   # "Auto kV Tissue": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//AutokVOptiCriteria",
                   #                                                                   "entry_node_xpath": ".//MlModeEntryType",
                   #                                                                   "entry_node_id_attrib": "@EntryNo",
                   #                                                                   "sub_node_xpath": "./MlModeScanType",
                   #                                                                   "sub_node_id_attrib": "@ModeScan",
                   #                                                                   "sub_node_id_value": "A"}),
                   # "Auto kV Min": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//AutokVVoltageMin",
                   #                                                                "entry_node_xpath": ".//MlModeEntryType",
                   #                                                                "entry_node_id_attrib": "@EntryNo",
                   #                                                                "sub_node_xpath": "./MlModeScanType",
                   #                                                                "sub_node_id_attrib": "@ModeScan",
                   #                                                                "sub_node_id_value": "A"}),
                   # "Auto kV Max": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//AutokVVoltageMax",
                   #                                                                "entry_node_xpath": ".//MlModeEntryType",
                   #                                                                "entry_node_id_attrib": "@EntryNo",
                   #                                                                "sub_node_xpath": "./MlModeScanType",
                   #                                                                "sub_node_id_attrib": "@ModeScan",
                   #                                                                "sub_node_id_value": "A"}),
                   "Dose Modulation On/Off": ("get_para_from_indiv_prot_xml_GE_Optima", {"para_xpath": "^automAFlag",
                                                                                         "in_group": True,
                                                                                         "in_recon": False,
                                                                                         "convert_to_val": True,
                                                                                         "convert_dict": {'0':"Off",'1':"On",'2':"Off"}}),
                   
                   "Dose Modulation Submode": ("get_para_from_indiv_prot_xml_GE_Optima", {"para_xpath": "^automaSubMode",
                                                                                  "in_group": True,
                                                                                  "in_recon": False,
                                                                                  "convert_to_val": True,
                                                                                  "convert_dict": {'0':"Off",'1':"SmartmA",'2':"SmartmA"}}),
                   
                   "Rotation Time (s)": ("get_para_from_indiv_prot_xml_GE_Optima", {"para_xpath": "^rotationTime",
                                                                                    "in_group": True,
                                                                                    "in_recon": False}),
                   
                   "Delay Time (s)": ("get_para_from_indiv_prot_xml_GE_Optima", {"para_xpath": "^groupDelay",
                                                                                 "in_group": True,
                                                                                 "in_recon": False}),
                   
                   "Pitch": ("get_para_from_indiv_prot_xml_GE_Optima", {"para_xpath": "^isd",
                                                                        "in_group": True,
                                                                        "in_recon": False}),
                   
                   "Slice No (Nominal)": ("get_para_from_indiv_prot_xml_GE_Optima", {"para_xpath": "^numberOfImages",
                                                                                     "in_group": True,
                                                                                     "in_recon": False}),
                   
                   # "Slice No (Actual)": ("get_para_from_indiv_prot_xml_GE_Optima", {"para_xpath": "^numImagesPerRotation",
                   #                                                                  "in_group": True,
                   #                                                                  "in_recon": False}),
                   
                   "Slice Width (mm)": ("get_para_from_indiv_prot_xml_GE_Optima", {"para_xpath": "^macroRowWidth",
                                                                                   "in_group": True,
                                                                                   "in_recon": False}),
                   
                   "Table Feed/Rotation (mm)": ("get_para_from_indiv_prot_xml_GE_Optima", {"para_xpath": "^tableSpeed",
                                                                                           "in_group": True,
                                                                                           "in_recon": False}),
                   
                   "Scan FOV (cm)": ("get_para_from_indiv_prot_xml_GE_Optima", {"para_xpath": "^scanFieldOfViewSize",
                                                                                "in_group": True,
                                                                                "in_recon": False}),
                   
                   # "Max recon FOV for TF (mm)": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//FoVMaxFlashTotal",
                   #                                                                              "entry_node_xpath": ".//MlModeEntryType",
                   #                                                                              "entry_node_id_attrib": "@EntryNo",
                   #                                                                              "sub_node_xpath": "./MlModeScanType",
                   #                                                                              "sub_node_id_attrib": "@ModeScan",
                   #                                                                              "sub_node_id_value": "A"}),
                   }

recon_lookup_tbl = {"Series Description": ("get_para_from_indiv_prot_xml_GE_Optima", {"para_xpath": "^seriesDescriptionRecon",
                                                                                      "in_group": True,
                                                                                      "in_recon": True}),
                    
                    "Slice Thickness (mm)": ("get_para_from_indiv_prot_xml_GE_Optima", {"para_xpath": "^PMRimageThickness",
                                                                                        "in_group": True,
                                                                                        "in_recon": True}),
                    
                    "Slice Increment (mm)": ("get_para_from_indiv_prot_xml_GE_Optima", {"para_xpath": "^PMRinterval",
                                                                                        "in_group": True,
                                                                                        "in_recon": True}),
                    
                    "Kernel": ("get_para_from_indiv_prot_xml_GE_Optima", {"para_xpath": "^algorithm",
                                                                          "in_group": True,
                                                                          "in_recon": True}),
                    
                    "Window Level": ("get_para_from_indiv_prot_xml_GE_Optima", {"para_xpath": "^filmingWl1S1",
                                                                               "in_group": True,
                                                                               "in_recon": True}),
                    
                    "Window Width": ("get_para_from_indiv_prot_xml_GE_Optima", {"para_xpath": "^filmingWw1S1",
                                                                               "in_group": True,
                                                                               "in_recon": True}),
                    
                    # "Window-1 Center": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//Window1Center",
                    #                                                                    "entry_node_xpath": ".//MlModeEntryType",
                    #                                                                    "entry_node_id_attrib": "@EntryNo",
                    #                                                                    "sub_node_xpath": "./MlModeReconType",
                    #                                                                    "sub_node_id_attrib": "@ReconJob"}),
                    # "Window-1 Width": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//Window1Width",
                    #                                                                   "entry_node_xpath": ".//MlModeEntryType",
                    #                                                                   "entry_node_id_attrib": "@EntryNo",
                    #                                                                   "sub_node_xpath": "./MlModeReconType",
                    #                                                                   "sub_node_id_attrib": "@ReconJob"}),
                    # "Window-2 Center": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//Window2Center",
                    #                                                                    "entry_node_xpath": ".//MlModeEntryType",
                    #                                                                    "entry_node_id_attrib": "@EntryNo",
                    #                                                                    "sub_node_xpath": "./MlModeReconType",
                    #                                                                    "sub_node_id_attrib": "@ReconJob"}),
                    # "Window-2 Width": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//Window2Width",
                    #                                                                   "entry_node_xpath": ".//MlModeEntryType",
                    #                                                                   "entry_node_id_attrib": "@EntryNo",
                    #                                                                   "sub_node_xpath": "./MlModeReconType",
                    #                                                                   "sub_node_id_attrib": "@ReconJob"}),
                    "Iter.Recon Type": ("get_para_from_indiv_prot_xml_GE_Optima", {"para_xpath": "^iterativeMode",
                                                                                   "in_group": True,
                                                                                   "in_recon": True}),
                    
                    "Iter.Recon Strength": ("get_para_from_indiv_prot_xml_GE_Optima", {"para_xpath": "^iterativeConfig",
                                                                                       "in_group": True,
                                                                                       "in_recon": True}),
                    
                    "Display FOV for Recon (mm)": ("get_para_from_indiv_prot_xml_GE_Optima", {"para_xpath": "^displayFieldOfView ",
                                                                                          "in_group": True,
                                                                                          "in_recon": True}),
                    
                    # "Vert FOV for Recon (mm)": ("get_para_from_indiv_prot_xml_GE_Optima", {"para_xpath": "^FoVVertLength:",
                    #                                                                        "in_group": "True"}),
                    
                    "Transfer1": ("get_para_from_indiv_prot_xml_GE_Optima", {"para_xpath": "^srSeriesAutoTransferDestination1",
                                                                             "in_group": False,
                                                                             "in_recon": False}),
                    
                    "Transfer2": ("get_para_from_indiv_prot_xml_GE_Optima", {"para_xpath": "^srSeriesAutoTransferDestination2",
                                                                             "in_group": False,
                                                                             "in_recon": False}),
                    
                    "Transfer3": ("get_para_from_indiv_prot_xml_GE_Optima", {"para_xpath": "^srSeriesAutoTransferDestination3",
                                                                             "in_group": False,
                                                                             "in_recon": False}),
                    # "Syngo TaskflowIdCode": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//TaskflowIdCode",
                    #                                                                         "entry_node_xpath": ".//MlModeEntryType",
                    #                                                                         "entry_node_id_attrib": "@EntryNo",
                    #                                                                         "sub_node_xpath": "./MlModeReconType",
                    #                                                                         "sub_node_id_attrib": "@ReconJob"}),
                    # "Syngo TaskflowProcessingIdCode": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//TaskflowProcessingIdCode",
                    #                                                                                   "entry_node_xpath": ".//MlModeEntryType",
                    #                                                                                   "entry_node_id_attrib": "@EntryNo",
                    #                                                                                   "sub_node_xpath": "./MlModeReconType",
                    #                                                                                   "sub_node_id_attrib": "@ReconJob"}),
                    # "Syngo TaskflowProcessingIdMeaning": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//TaskflowProcessingIdMeaning",
                    #                                                                                      "entry_node_xpath": ".//MlModeEntryType",
                    #                                                                                      "entry_node_id_attrib": "@EntryNo",
                    #                                                                                      "sub_node_xpath": "./MlModeReconType",
                    #                                                                                      "sub_node_id_attrib": "@ReconJob"}),
                    # "Comment1": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//Comment1",
                    #                                                             "entry_node_xpath": ".//MlModeEntryType",
                    #                                                             "entry_node_id_attrib": "@EntryNo",
                    #                                                             "sub_node_xpath": "./MlModeReconType",
                    #                                                             "sub_node_id_attrib": "@ReconJob"}),
                    # "Comment2": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//Comment1",
                    #                                                             "entry_node_xpath": ".//MlModeEntryType",
                    #                                                             "entry_node_id_attrib": "@EntryNo",
                    #                                                             "sub_node_xpath": "./MlModeReconType",
                    #                                                             "sub_node_id_attrib": "@ReconJob"}),
                    }

# for pre-monitoring and monitoring scans
monitoring_scan_lookup_tbl = {"Range": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//RangeName",
                                                                                       "entry_node_xpath": ".//MlModeEntryType",
                                                                                       "entry_node_id_attrib": "@EntryNo",
                                                                                       "sub_node_xpath": "./MlModeScanType"}),
                              # "Scan Mode": ("calculate_scan_para_Siemens_Force", {}),
                              "Reference kVp": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//QualityReferenceVoltage",
                                                                                               "entry_node_xpath": ".//MlModeEntryType",
                                                                                               "entry_node_id_attrib": "@EntryNo",
                                                                                               "sub_node_xpath": "./MlModeScanType"}),
                              "kVp": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//Voltage",
                                                                                     "entry_node_xpath": ".//MlModeEntryType",
                                                                                     "entry_node_id_attrib": "@EntryNo",
                                                                                     "sub_node_xpath": "./MlModeScanType"}),
                              "Qref mAs": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//QualityReferencemAs",
                                                                                          "entry_node_xpath": ".//MlModeEntryType",
                                                                                          "entry_node_id_attrib": "@EntryNo",
                                                                                          "sub_node_xpath": "./MlModeScanType"}),
                              "mAs": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//CustomMAs",
                                                                                     "entry_node_xpath": ".//MlModeEntryType",
                                                                                     "entry_node_id_attrib": "@EntryNo",
                                                                                     "sub_node_xpath": "./MlModeScanType"}),
                              "Auto kV Mode": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//AutokVMode",
                                                                                              "entry_node_xpath": ".//MlModeEntryType",
                                                                                              "entry_node_id_attrib": "@EntryNo",
                                                                                              "sub_node_xpath": "./MlModeScanType"}),
                              # "Auto kV Tissue": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//AutokVOptiCriteria",
                              #                                                                   "entry_node_xpath": ".//MlModeEntryType",
                              #                                                                   "entry_node_id_attrib": "@EntryNo",
                              #                                                                   "sub_node_xpath": "./MlModeScanType"}),
                              # "Auto kV Min": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//AutokVVoltageMin",
                              #                                                                "entry_node_xpath": ".//MlModeEntryType",
                              #                                                                "entry_node_id_attrib": "@EntryNo",
                              #                                                                "sub_node_xpath": "./MlModeScanType"}),
                              # "Auto kV Max": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//AutokVVoltageMax",
                              #                                                                "entry_node_xpath": ".//MlModeEntryType",
                              #                                                                "entry_node_id_attrib": "@EntryNo",
                              #                                                                "sub_node_xpath": "./MlModeScanType"}),
                              "Dose Modulation On/Off": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//Care",
                                                                                                        "entry_node_xpath": ".//MlModeEntryType",
                                                                                                        "entry_node_id_attrib": "@EntryNo",
                                                                                                        "sub_node_xpath": "./MlModeScanType"}),
                              # "Dose Modulation": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//CareDoseType",
                              #                                                                    "entry_node_xpath": ".//MlModeEntryType",
                              #                                                                    "entry_node_id_attrib": "@EntryNo",
                              #                                                                    "sub_node_xpath": "./MlModeScanType"}),
                              "Rotation Time (s)": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//ExposureTimePerRotation",
                                                                                                   "entry_node_xpath": ".//MlModeEntryType",
                                                                                                   "entry_node_id_attrib": "@EntryNo",
                                                                                                   "sub_node_xpath": "./MlModeScanType"}),
                              "Delay Time (s)": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//StartDelay",
                                                                                                "entry_node_xpath": ".//MlModeEntryType",
                                                                                                "entry_node_id_attrib": "@EntryNo",
                                                                                                "sub_node_xpath": "./MlModeScanType"}),
                              "Pitch": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//PitchFactor",
                                                                                       "entry_node_xpath": ".//MlModeEntryType",
                                                                                       "entry_node_id_attrib": "@EntryNo",
                                                                                       "sub_node_xpath": "./MlModeScanType"}),
                              # "Slice No (Nominal)": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//NoOfSlicesEffective",
                              #                                                                       "entry_node_xpath": ".//MlModeEntryType",
                              #                                                                       "entry_node_id_attrib": "@EntryNo",
                              #                                                                       "sub_node_xpath": "./MlModeScanType"}),
                              "Slice No (Actual)": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//NoOfSlicesActual",
                                                                                                   "entry_node_xpath": ".//MlModeEntryType",
                                                                                                   "entry_node_id_attrib": "@EntryNo",
                                                                                                   "sub_node_xpath": "./MlModeScanType"}),
                              "Slice Width (mm)": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//SliceWidthCollimated",
                                                                                             "entry_node_xpath": ".//MlModeEntryType",
                                                                                             "entry_node_id_attrib": "@EntryNo",
                                                                                             "sub_node_xpath": "./MlModeScanType"}),
                              # "Table Feed/Rotation (mm)": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//SpiralFeedRot",
                              #                                                                             "entry_node_xpath": ".//MlModeEntryType",
                              #                                                                             "entry_node_id_attrib": "@EntryNo",
                              #                                                                             "sub_node_xpath": "./MlModeScanType"}),
                              "Scan FOV (mm)": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//FOVLimitForThreshold",
                                                                                               "entry_node_xpath": ".//MlModeEntryType",
                                                                                               "entry_node_id_attrib": "@EntryNo",
                                                                                               "sub_node_xpath": "./MlModeScanType"}),
                              "No of Scans": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//NoOfScans",
                                                                                             "entry_node_xpath": ".//MlModeEntryType",
                                                                                             "entry_node_id_attrib": "@EntryNo",
                                                                                             "sub_node_xpath": "./MlModeScanType"}),
                              }

de_scan_lookup_tbl = {"Range": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//RangeName",
                                                                               "entry_node_xpath": ".//MlModeEntryType",
                                                                               "entry_node_id_attrib": "@EntryNo",
                                                                               "sub_node_xpath": "./MlModeScanType"}),
                      # "Scan Mode": ("calculate_scan_para_Siemens_Force", {}),
                      "Reference kVp": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//QualityReferenceVoltage",
                                                                                       "entry_node_xpath": ".//MlModeEntryType",
                                                                                       "entry_node_id_attrib": "@EntryNo",
                                                                                       "sub_node_xpath": "./MlModeScanType"}),
                      "kVp": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//Voltage",
                                                                             "entry_node_xpath": ".//MlModeEntryType",
                                                                             "entry_node_id_attrib": "@EntryNo",
                                                                             "sub_node_xpath": "./MlModeScanType"}),
                      "Qref mAs": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//QualityReferencemAs",
                                                                                  "entry_node_xpath": ".//MlModeEntryType",
                                                                                  "entry_node_id_attrib": "@EntryNo",
                                                                                  "sub_node_xpath": "./MlModeScanType"}),
                      "Eff. mAs": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//EffectiveMAs",
                                                                                  "entry_node_xpath": ".//MlModeEntryType",
                                                                                  "entry_node_id_attrib": "@EntryNo",
                                                                                  "sub_node_xpath": "./MlModeScanType"}),
                      "Auto kV Mode": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//AutokVMode",
                                                                                      "entry_node_xpath": ".//MlModeEntryType",
                                                                                      "entry_node_id_attrib": "@EntryNo",
                                                                                      "sub_node_xpath": "./MlModeScanType"}),
                      "Auto kV Tissue": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//AutokVOptiCriteria",
                                                                                        "entry_node_xpath": ".//MlModeEntryType",
                                                                                        "entry_node_id_attrib": "@EntryNo",
                                                                                        "sub_node_xpath": "./MlModeScanType"}),
                      "Auto kV Min": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//AutokVVoltageMin",
                                                                                     "entry_node_xpath": ".//MlModeEntryType",
                                                                                     "entry_node_id_attrib": "@EntryNo",
                                                                                     "sub_node_xpath": "./MlModeScanType"}),
                      "Auto kV Max": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//AutokVVoltageMax",
                                                                                     "entry_node_xpath": ".//MlModeEntryType",
                                                                                     "entry_node_id_attrib": "@EntryNo",
                                                                                     "sub_node_xpath": "./MlModeScanType"}),
                      "Dose Modulation On/Off": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//Care",
                                                                                                "entry_node_xpath": ".//MlModeEntryType",
                                                                                                "entry_node_id_attrib": "@EntryNo",
                                                                                                "sub_node_xpath": "./MlModeScanType"}),
                      "Dose Modulation": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//CareDoseType",
                                                                                         "entry_node_xpath": ".//MlModeEntryType",
                                                                                         "entry_node_id_attrib": "@EntryNo",
                                                                                         "sub_node_xpath": "./MlModeScanType"}),
                      "Rotation Time (s)": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//ExposureTimePerRotation",
                                                                                           "entry_node_xpath": ".//MlModeEntryType",
                                                                                           "entry_node_id_attrib": "@EntryNo",
                                                                                           "sub_node_xpath": "./MlModeScanType"}),
                      "Delay Time (s)": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//StartDelay",
                                                                                        "entry_node_xpath": ".//MlModeEntryType",
                                                                                        "entry_node_id_attrib": "@EntryNo",
                                                                                        "sub_node_xpath": "./MlModeScanType"}),
                      "Pitch": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//PitchFactor",
                                                                               "entry_node_xpath": ".//MlModeEntryType",
                                                                               "entry_node_id_attrib": "@EntryNo",
                                                                               "sub_node_xpath": "./MlModeScanType"}),
                      "Slice No (Nominal)": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//NoOfSlicesEffective",
                                                                                            "entry_node_xpath": ".//MlModeEntryType",
                                                                                            "entry_node_id_attrib": "@EntryNo",
                                                                                            "sub_node_xpath": "./MlModeScanType"}),
                      "Slice No (Actual)": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//NoOfSlicesActual",
                                                                                           "entry_node_xpath": ".//MlModeEntryType",
                                                                                           "entry_node_id_attrib": "@EntryNo",
                                                                                           "sub_node_xpath": "./MlModeScanType"}),
                      "Slice Width (mm)": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//SliceWidthCollimated",
                                                                                          "entry_node_xpath": ".//MlModeEntryType",
                                                                                          "entry_node_id_attrib": "@EntryNo",
                                                                                          "sub_node_xpath": "./MlModeScanType"}),
                      "Table Feed/Rotation (mm)": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//SpiralFeedRot",
                                                                                                  "entry_node_xpath": ".//MlModeEntryType",
                                                                                                  "entry_node_id_attrib": "@EntryNo",
                                                                                                  "sub_node_xpath": "./MlModeScanType"}),
                      "Scan FOV (mm)": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//FOVLimitForThreshold",
                                                                                       "entry_node_xpath": ".//MlModeEntryType",
                                                                                       "entry_node_id_attrib": "@EntryNo",
                                                                                       "sub_node_xpath": "./MlModeScanType"}),
                      "Max recon FOV for TF (mm)": ("get_para_from_indiv_prot_xml_Siemens_Force", {"para_xpath": ".//FoVMaxFlashTotal",
                                                                                                   "entry_node_xpath": ".//MlModeEntryType",
                                                                                                   "entry_node_id_attrib": "@EntryNo",
                                                                                                   "sub_node_xpath": "./MlModeScanType"}),
                      }

# save lookup tables into json
# save lookup tables to json files
print("saved topo_lookup_tbl to ./para_lookup_tbl/GE/topo_lookup_tbl_GE.json")
with open('./para_lookup_tbl/GE/topo_lookup_tbl_GE.json', 'w') as fp:
    json.dump(topo_lookup_tbl, fp, indent=4)

print("saved scan_lookup_tbl to ./para_lookup_tbl/GE/scan_lookup_tbl_GE.json")
with open('./para_lookup_tbl/GE/scan_lookup_tbl_GE.json', 'w') as fp:
    json.dump(scan_lookup_tbl, fp, indent=4)

print("saved recon_lookup_tbl to ./para_lookup_tbl/GE/recon_lookup_tbl_GE.json")
with open('./para_lookup_tbl/GE/recon_lookup_tbl_GE.json', 'w') as fp:
    json.dump(recon_lookup_tbl, fp, indent=4)

print("saved monitoring_scan_lookup_tbl to ./para_lookup_tbl/GE/monitoring_scan_lookup_tbl_GE.json")
with open('./para_lookup_tbl/GE/monitoring_scan_lookup_tbl_GE.json', 'w') as fp:
    json.dump(monitoring_scan_lookup_tbl, fp, indent=4)
