# Filename: decompose_concat_protocol_name.py
"""Summary: decompose the concatenated protocol name which is generated by DoseMonitor


"""
# Author: Da Zhang, PhD, DABR
# Created: Fri Apr 23 23:29:08 2021
# Last-Updated: Tue May 18 22:41:46 2021 (-14400 Eastern Daylight Time)
#      Update #: 9


def truncate_concat_protocol_name(scan_protocol_name,
                                  separator='|'):

    assert isinstance(scan_protocol_name, str)

    return scan_protocol_name.split(separator)[-1]

def extract_protocol_name_per_scanner(scan_protocol_name,
                                      scanner_name,
                                      separator='|'):
    assert isinstance(scan_protocol_name, str)
        
    return scan_protocol_name.split(separator)[0]
